GET  http://localhost:3001/contacts?orderBy=desc

###
GET  http://localhost:3001/contacts/e79733e0-9238-4e36-84e7-aea49bb827ea

###
DELETE  http://localhost:3001/contacts/e79733e0-9238-4e36-84e7-aea49bb827ea

###
POST  http://localhost:3001/contacts HTTP/1.1
content-type: application/json

{
    "id": 1,
    "name": "Jôsue",
    "email": "josue.teixeira2234@teste.com.br",
    "phone": "9999-11111"
}

###
PUT  http://localhost:3001/contacts/a00387cd-8018-49ee-a966-befc4a0c5c42 HTTP/1.1
content-type: application/json

{
    "name": "Matheus Andreatta",
    "email": "matheus.andreatta@teste.com.br"
}
