GET  http://localhost:3001/contacts?orderBy=desc

###
GET  http://localhost:3001/contacts/729c202c-9ab4-4b83-8c3e-616613444a7e

###
DELETE  http://localhost:3001/contacts/729c202c-9ab4-4b83-8c3e-616613444a7e

###
POST  http://localhost:3001/contacts HTTP/1.1
content-type: application/json

{
    "name": "Matheus Andreatta",
    "email": "matheus.andreatta@web.com.br",
    "phone": "9999-11111"
}

###
PUT  http://localhost:3001/contacts/a00387cd-8018-49ee-a966-befc4a0c5c42 HTTP/1.1
content-type: application/json

{
    "name": "Matheus Andreatta",
    "email": "matheus.andreatta@teste.com.br"
}
